services:
  web-server:
    build:
      context: .
      dockerfile: ./web-server/Dockerfile
      args:
        BASE_URL: ${HOST_URL}
    ports:
      - "80:80"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - API_SECRET=${API_SECRET}
    depends_on:
      - db
    restart: unless-stopped
  
  media-server:
    build:
      context: .
      dockerfile: ./media-server/Dockerfile
    ports:
      - "8081:8081"
    expose:
      - "1234"
    volumes:
      - ${MEDIA_HOST_PATH}:/app/media
    environment:
      - MEDIA_DIR=/app/media
      - DATABASE_URL=postgres://user:password@db:5432/media
    depends_on:
      - web-server
      - db
    restart: unless-stopped

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=media
    volumes:
      - media_db:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - "5432:5432"

volumes:
  media_db:
