// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type HasWatchedMovie struct {
	MovieID int32
	UserID  int32
}

type HasWatchedTv struct {
	TvID   int32
	UserID int32
}

type Movie struct {
	ID          int32
	Title       string
	ReleaseYear int32
	FilePath    string
	ImgUrl      sql.NullString
}

type TvShow struct {
	ID            int32
	Name          string
	SeasonNumber  int32
	EpisodeNumber int32
	FilePath      string
	ReleaseYear   int32
	ImgUrl        sql.NullString
}

type User struct {
	ID       int32
	UserName string
	PwHash   string
}
