// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	CreateMovie(ctx context.Context, arg CreateMovieParams) (Movie, error)
	CreateTVShow(ctx context.Context, arg CreateTVShowParams) (TvShow, error)
	CreateTVShowWatch(ctx context.Context, arg CreateTVShowWatchParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteTVShow(ctx context.Context, id int32) (string, error)
	DeleteTVShowWatch(ctx context.Context, arg DeleteTVShowWatchParams) error
	// -- name: GetMovies :many
	// SELECT * FROM movies;
	GetMovie(ctx context.Context, id int32) (Movie, error)
	GetMovies(ctx context.Context, userName string) ([]GetMoviesRow, error)
	GetTVShows(ctx context.Context, userName string) ([]GetTVShowsRow, error)
	GetUser(ctx context.Context, id int32) (User, error)
	GetUserByName(ctx context.Context, userName string) (User, error)
}

var _ Querier = (*Queries)(nil)
